version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kle
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - kle-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8


  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kle-db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - kle-network

networks:
  kle-network:

volumes:
  mysql-data:
